# Generated by Django 4.2.8 on 2024-01-09 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_techstac'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechStac',
            new_name='TechStack',
        ),
    ]
